AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"
    - "tmp/**/*"
    - "ext/**/*"
    - "test/test_*.rb"  # Test fixture files (sample Ruby code for testing)

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25
